version: "3.4"

services:
#  frontend:
#    build: "./client_web"
#    restart: always
#    depends_on:
#      - client_mobile
#    ports:
#      - "8081:8081"
#    volumes:
#      - apk:/mobile_app/

  client_mobile:
    build: './client_mobile'
    volumes:
      - apk:/mobile_app/


networks:
  backend:

volumes:
  apk:
  db-data: